class AccountTitle {
  const AccountTitle({
    required this.id,
    required this.prefixIndex,
    required this.roleIndex,
  });

  final String id;
  final int prefixIndex;
  final int roleIndex;

  String label(String languageCode) {
    final words =
        _localizedTitleWords[languageCode] ?? _localizedTitleWords['en']!;
    return '${words.prefixes[prefixIndex]} ${words.roles[roleIndex]}';
  }
}

class _TitleWords {
  const _TitleWords(this.prefixes, this.roles);

  final List<String> prefixes;
  final List<String> roles;
}

const Map<String, _TitleWords> _localizedTitleWords = {
  'en': _TitleWords(
    [
      'Ancient',
      'Astral',
      'Blazing',
      'Celestial',
      'Crystal',
      'Daring',
      'Dawn',
      'Dreaming',
      'Ember',
      'Enchanted',
      'Eternal',
      'Fabled',
      'Frost',
      'Golden',
      'Hidden',
      'Infernal',
      'Moonlit',
      'Prismatic',
      'Radiant',
      'Royal',
      'Runic',
      'Shadow',
      'Silver',
      'Starborn',
      'Storm',
    ],
    [
      'Dragon Keeper',
      'Egg Whisperer',
      'Nest Guardian',
      'Scale Scholar',
      'Tower Warden',
      'Flame Friend',
      'Hoard Curator',
      'Wyrm Watcher',
      'Sky Seeker',
      'Rune Reader',
      'Moon Rider',
      'Gem Finder',
      'Chest Charmer',
      'Lore Weaver',
      'Cloud Walker',
      'Spark Tamer',
      'Wing Guide',
      'Haven Herald',
      'Drake Dreamer',
      'Star Sentinel',
    ],
  ),
  'nl': _TitleWords(
    [
      'Oude',
      'Astrale',
      'Vlammende',
      'Hemelse',
      'Kristallen',
      'Dappere',
      'Dageraad',
      'Dromende',
      'Gloeiende',
      'Betoverde',
      'Eeuwige',
      'Legendarische',
      'IJzige',
      'Gouden',
      'Verborgen',
      'Inferno',
      'Maanlichte',
      'Prismatische',
      'Stralende',
      'Koninklijke',
      'Runen',
      'Schaduw',
      'Zilveren',
      'Sterren',
      'Stormachtige',
    ],
    [
      'Drakenhoeder',
      'Eifluisteraar',
      'Nestbewaker',
      'Schubgeleerde',
      'Torenwachter',
      'Vlamvriend',
      'Schatbeheerder',
      'Draakwachter',
      'Hemelzoeker',
      'Runenlezer',
      'Maanrijder',
      'Edelsteenvinder',
      'Kistbetoveraar',
      'Lorewever',
      'Wolkenloper',
      'Vonktemmer',
      'Vleugelgids',
      'Havenheraut',
      'Drakendromer',
      'Sterrenwachter',
    ],
  ),
  'de': _TitleWords(
    [
      'Uralter',
      'Astraler',
      'Lodernder',
      'Himmlischer',
      'Kristallener',
      'Kühner',
      'Dämmerungs',
      'Träumender',
      'Glut',
      'Verzauberter',
      'Ewiger',
      'Sagenhafter',
      'Frostiger',
      'Goldener',
      'Verborgener',
      'Infernalischer',
      'Mondheller',
      'Prismatischer',
      'Strahlender',
      'Königlicher',
      'Runischer',
      'Schatten',
      'Silberner',
      'Sterngeborener',
      'Stürmischer',
    ],
    [
      'Drachenhüter',
      'Eierflüsterer',
      'Nestwächter',
      'Schuppengelehrter',
      'Turmwächter',
      'Flammenfreund',
      'Hortkurator',
      'Drachenbeobachter',
      'Himmelssucher',
      'Runenleser',
      'Mondreiter',
      'Edelsteinfinder',
      'Truhenzauberer',
      'Sagenweber',
      'Wolkenläufer',
      'Funkenzähmer',
      'Flügelführer',
      'Havenherold',
      'Drachenträumer',
      'Sternenwächter',
    ],
  ),
  'fr': _TitleWords(
    [
      'Ancien',
      'Astral',
      'Ardent',
      'Céleste',
      'Cristallin',
      'Audacieux',
      'de l’Aube',
      'Rêveur',
      'de Braise',
      'Enchanté',
      'Éternel',
      'Fabuleux',
      'de Givre',
      'Doré',
      'Caché',
      'Infernal',
      'au Clair de Lune',
      'Prismatique',
      'Rayonnant',
      'Royal',
      'Runique',
      'des Ombres',
      'Argenté',
      'Né des Étoiles',
      'de Tempête',
    ],
    [
      'Gardien des Dragons',
      'Chuchoteur d’Œufs',
      'Gardien du Nid',
      'Savant des Écailles',
      'Gardien de la Tour',
      'Ami des Flammes',
      'Conservateur du Trésor',
      'Veilleur de Dragons',
      'Chercheur du Ciel',
      'Lecteur de Runes',
      'Cavalier Lunaire',
      'Trouveur de Gemmes',
      'Charmeur de Coffres',
      'Tisseur de Légendes',
      'Marcheur des Nuages',
      'Dompteur d’Étincelles',
      'Guide des Ailes',
      'Héraut du Havre',
      'Rêveur de Dragons',
      'Sentinelle des Étoiles',
    ],
  ),
  'es': _TitleWords(
    [
      'Antiguo',
      'Astral',
      'Ardiente',
      'Celestial',
      'Cristalino',
      'Audaz',
      'del Alba',
      'Soñador',
      'de Brasa',
      'Encantado',
      'Eterno',
      'Legendario',
      'de Escarcha',
      'Dorado',
      'Oculto',
      'Infernal',
      'Lunar',
      'Prismático',
      'Radiante',
      'Real',
      'Rúnico',
      'Sombrío',
      'Plateado',
      'Nacido de las Estrellas',
      'Tormentoso',
    ],
    [
      'Guardián de Dragones',
      'Susurrador de Huevos',
      'Guardián del Nido',
      'Erudito de Escamas',
      'Guardián de la Torre',
      'Amigo de las Llamas',
      'Curador del Tesoro',
      'Vigilante de Dragones',
      'Buscador del Cielo',
      'Lector de Runas',
      'Jinete Lunar',
      'Buscador de Gemas',
      'Encantador de Cofres',
      'Tejedor de Leyendas',
      'Caminante de Nubes',
      'Domador de Chispas',
      'Guía de Alas',
      'Heraldo del Refugio',
      'Soñador de Dragones',
      'Centinela Estelar',
    ],
  ),
  'it': _TitleWords(
    [
      'Antico',
      'Astrale',
      'Fiammeggiante',
      'Celestiale',
      'Cristallino',
      'Audace',
      'dell’Alba',
      'Sognante',
      'della Brace',
      'Incantato',
      'Eterno',
      'Leggendario',
      'Gelido',
      'Dorato',
      'Nascosto',
      'Infernale',
      'Lunare',
      'Prismatico',
      'Radioso',
      'Regale',
      'Runico',
      'd’Ombra',
      'Argenteo',
      'Nato dalle Stelle',
      'Tempestoso',
    ],
    [
      'Custode dei Draghi',
      'Sussurratore di Uova',
      'Guardiano del Nido',
      'Studioso di Scaglie',
      'Guardiano della Torre',
      'Amico delle Fiamme',
      'Curatore del Tesoro',
      'Osservatore di Draghi',
      'Cercatore del Cielo',
      'Lettore di Rune',
      'Cavaliere Lunare',
      'Cercatore di Gemme',
      'Incantatore di Scrigni',
      'Tessitore di Leggende',
      'Camminatore di Nuvole',
      'Domatore di Scintille',
      'Guida delle Ali',
      'Araldo del Rifugio',
      'Sognatore di Draghi',
      'Sentinella Stellare',
    ],
  ),
  'pt': _TitleWords(
    [
      'Antigo',
      'Astral',
      'Flamejante',
      'Celestial',
      'Cristalino',
      'Audaz',
      'da Aurora',
      'Sonhador',
      'da Brasa',
      'Encantado',
      'Eterno',
      'Lendário',
      'Glacial',
      'Dourado',
      'Oculto',
      'Infernal',
      'Lunar',
      'Prismático',
      'Radiante',
      'Real',
      'Rúnico',
      'Sombrio',
      'Prateado',
      'Nascido das Estrelas',
      'Tempestuoso',
    ],
    [
      'Guardião de Dragões',
      'Sussurrador de Ovos',
      'Guardião do Ninho',
      'Sábio das Escamas',
      'Guardião da Torre',
      'Amigo das Chamas',
      'Curador do Tesouro',
      'Observador de Dragões',
      'Buscador do Céu',
      'Leitor de Runas',
      'Cavaleiro Lunar',
      'Caçador de Gemas',
      'Encantador de Baús',
      'Tecelão de Lendas',
      'Caminhante das Nuvens',
      'Domador de Faíscas',
      'Guia das Asas',
      'Arauto do Refúgio',
      'Sonhador de Dragões',
      'Sentinela Estelar',
    ],
  ),
  'ja': _TitleWords(
    [
      '古代の',
      '星界の',
      '炎の',
      '天空の',
      '水晶の',
      '勇敢な',
      '暁の',
      '夢見る',
      '残り火の',
      '魔法の',
      '永遠の',
      '伝説の',
      '霜の',
      '黄金の',
      '隠された',
      '地獄の',
      '月明かりの',
      '虹彩の',
      '輝く',
      '王家の',
      'ルーンの',
      '影の',
      '銀の',
      '星生まれの',
      '嵐の',
    ],
    [
      'ドラゴンキーパー',
      '卵のささやき手',
      '巣の守護者',
      '鱗の学者',
      '塔の番人',
      '炎の友',
      '宝物の管理人',
      'ドラゴンの見張り役',
      '空の探求者',
      'ルーンの読解者',
      '月の騎手',
      '宝石の発見者',
      '宝箱の魔術師',
      '伝承の織り手',
      '雲の歩行者',
      '火花の調教師',
      '翼の案内人',
      '安息地の伝令',
      'ドラゴンの夢想家',
      '星の番人',
    ],
  ),
};

final List<AccountTitle> accountTitleCatalog = List.unmodifiable(
  List.generate(500, (index) {
    final number = index + 1;
    return AccountTitle(
      id: 'title_${number.toString().padLeft(3, '0')}',
      prefixIndex: index ~/ 20,
      roleIndex: index % 20,
    );
  }),
);

final Map<String, AccountTitle> _accountTitlesById = Map.unmodifiable({
  for (final title in accountTitleCatalog) title.id: title,
});

AccountTitle? accountTitleById(String? id) =>
    id == null ? null : _accountTitlesById[id];
