enum AchievementCategory { starter, easy, challenging, master }

class AchievementDefinition {
  const AchievementDefinition(
      {required this.id,
      required this.titleEn,
      required this.titleNl,
      required this.descriptionEn,
      required this.descriptionNl,
      required this.target,
      required this.category,
      this.secret = false,
      this.badge = 'shield'});
  final String id;
  final String titleEn;
  final String titleNl;
  final String descriptionEn;
  final String descriptionNl;
  final int target;
  final AchievementCategory category;
  final bool secret;
  final String badge;
}

const achievementCatalog = <AchievementDefinition>[
  AchievementDefinition(
      id: 'hello_little_one',
      titleEn: 'Hello, Little One!',
      titleNl: 'Hallo, Kleintje!',
      descriptionEn: 'Hatch your Starter Egg.',
      descriptionNl: 'Laat je Starter Egg uitkomen.',
      target: 1,
      category: AchievementCategory.starter,
      badge: 'egg'),
  AchievementDefinition(
      id: 'first_flight',
      titleEn: 'First Flight',
      titleNl: 'Eerste Vlucht',
      descriptionEn: 'Complete your first Short Adventure.',
      descriptionNl: 'Voltooi je eerste Short Adventure.',
      target: 1,
      category: AchievementCategory.easy,
      badge: 'flight'),
  AchievementDefinition(
      id: 'chest_expectations',
      titleEn: 'Chest Expectations',
      titleNl: 'Kistverwachtingen',
      descriptionEn: 'Open your first chest.',
      descriptionNl: 'Open je eerste kist.',
      target: 1,
      category: AchievementCategory.easy,
      badge: 'chest'),
  AchievementDefinition(
      id: 'room_to_roost',
      titleEn: 'Room to Roost',
      titleNl: 'Ruimte om te Rusten',
      descriptionEn: 'Buy your first extra Dragon Tower floor.',
      descriptionNl: 'Koop je eerste extra verdieping in de Dragon Tower.',
      target: 2,
      category: AchievementCategory.easy,
      badge: 'tower'),
  AchievementDefinition(
      id: 'feed_furniture',
      titleEn: 'Do Not Feed the Furniture',
      titleNl: 'Voer het Meubilair Niet',
      descriptionEn: 'Place your first furniture item.',
      descriptionNl: 'Plaats je eerste meubelstuk.',
      target: 1,
      category: AchievementCategory.easy,
      badge: 'chair'),
  AchievementDefinition(
      id: 'book_wyrm',
      titleEn: 'Book Wyrm',
      titleNl: 'Boekenwyrm',
      descriptionEn: 'Discover 5 normal dragon families.',
      descriptionNl: 'Ontdek 5 normale drakenfamilies.',
      target: 5,
      category: AchievementCategory.easy,
      badge: 'book'),
  AchievementDefinition(
      id: 'growing_pains',
      titleEn: 'Growing Pains',
      titleNl: 'Groeipijnen',
      descriptionEn: 'Evolve a Hatchling into a Wyrmling.',
      descriptionNl: 'Laat een Hatchling evolueren naar een Wyrmling.',
      target: 1,
      category: AchievementCategory.easy,
      badge: 'spark'),
  AchievementDefinition(
      id: 'not_picking_favorites',
      titleEn: 'Definitely Not Picking Favorites',
      titleNl: 'Zeker Geen Favorieten Kiezen',
      descriptionEn: 'Mark a dragon as favorite.',
      descriptionNl: 'Markeer een draak als favoriet.',
      target: 1,
      category: AchievementCategory.easy,
      badge: 'heart'),
  AchievementDefinition(
      id: 'halfway_clouds',
      titleEn: 'Halfway to the Clouds',
      titleNl: 'Halverwege de Wolken',
      descriptionEn: 'Build 10 Dragon Tower floors.',
      descriptionNl: 'Bouw 10 verdiepingen in de Dragon Tower.',
      target: 10,
      category: AchievementCategory.challenging,
      badge: 'tower'),
  AchievementDefinition(
      id: 'ascension_day',
      titleEn: 'Ascension Day',
      titleNl: 'Hemelvaartsdag',
      descriptionEn: 'Evolve your first Ascended dragon.',
      descriptionNl: 'Laat je eerste draak Ascended worden.',
      target: 1,
      category: AchievementCategory.challenging,
      badge: 'ascend'),
  AchievementDefinition(
      id: 'something_spectral',
      titleEn: 'Something Spectral This Way Comes',
      titleNl: 'Er Komt Iets Spectraals Aan',
      descriptionEn: 'Discover your first Spectral dragon.',
      descriptionNl: 'Ontdek je eerste Spectral-draak.',
      target: 1,
      category: AchievementCategory.challenging,
      badge: 'spectral'),
  AchievementDefinition(
      id: 'well_read_scaled',
      titleEn: 'Well Read, Well Scaled',
      titleNl: 'Goed Gelezen, Goed Geschubd',
      descriptionEn: 'Discover 20 normal dragon families.',
      descriptionNl: 'Ontdek 20 normale drakenfamilies.',
      target: 20,
      category: AchievementCategory.challenging,
      badge: 'book'),
  AchievementDefinition(
      id: 'frequent_flyer',
      titleEn: 'Frequent Flyer',
      titleNl: 'Vaste Vlieger',
      descriptionEn: 'Complete 50 Adventures.',
      descriptionNl: 'Voltooi 50 Adventures.',
      target: 50,
      category: AchievementCategory.challenging,
      badge: 'flight'),
  AchievementDefinition(
      id: 'full_party',
      titleEn: 'Full Party, Full Send',
      titleNl: 'Volle Groep, Vol Erin',
      descriptionEn: 'Complete a Group Adventure with 4 participants.',
      descriptionNl: 'Voltooi een Group Adventure met 4 deelnemers.',
      target: 1,
      category: AchievementCategory.challenging,
      badge: 'group'),
  AchievementDefinition(
      id: 'came_crawling_back',
      titleEn: 'Look Who Came Crawling Back',
      titleNl: 'Kijk Wie Terug Kwam Kruipen',
      descriptionEn: 'Receive a weekly visit from a released dragon.',
      descriptionNl: 'Krijg wekelijks bezoek van een vrijgelaten draak.',
      target: 1,
      category: AchievementCategory.challenging,
      badge: 'return'),
  AchievementDefinition(
      id: 'sky_ceiling',
      titleEn: 'The Sky Has a Ceiling After All',
      titleNl: 'De Lucht Heeft Toch een Plafond',
      descriptionEn: 'Reach 20 Dragon Tower floors.',
      descriptionNl: 'Bereik 20 verdiepingen in de Dragon Tower.',
      target: 20,
      category: AchievementCategory.master,
      badge: 'tower'),
  AchievementDefinition(
      id: 'scale_every_tale',
      titleEn: 'A Scale for Every Tale',
      titleNl: 'Een Schub voor Elk Verhaal',
      descriptionEn: 'Discover all 42 normal dragon families.',
      descriptionNl: 'Ontdek alle 42 normale drakenfamilies.',
      target: 42,
      category: AchievementCategory.master,
      badge: 'book'),
  AchievementDefinition(
      id: 'ghost_writer',
      titleEn: 'Ghost Writer',
      titleNl: 'Spookschrijver',
      descriptionEn: 'Discover Spectral forms of 10 families.',
      descriptionNl: 'Ontdek Spectral-vormen van 10 families.',
      target: 10,
      category: AchievementCategory.master,
      badge: 'spectral'),
  AchievementDefinition(
      id: 'myth_made_real',
      titleEn: 'Myth Made Real',
      titleNl: 'Mythe Wordt Werkelijk',
      descriptionEn: 'Obtain a Mythical-family dragon.',
      descriptionNl: 'Verkrijg een draak uit de Mythical-familie.',
      target: 1,
      category: AchievementCategory.master,
      badge: 'myth'),
  AchievementDefinition(
      id: 'probably_fine',
      titleEn: 'This Is Probably Fine',
      titleNl: 'Dit Komt Vast Goed',
      descriptionEn: 'Complete a Sinister Special Adventure.',
      descriptionNl: 'Voltooi een Sinister Special Adventure.',
      target: 1,
      category: AchievementCategory.master,
      secret: true,
      badge: 'sinister'),
];
