enum AchievementCategory { starter, easy, challenging, master }

class AchievementDefinition {
  const AchievementDefinition(
      {required this.id,
      required this.titleEn,
      required this.titleNl,
      required this.descriptionEn,
      required this.descriptionNl,
      required this.target,
      required this.category,
      this.secret = false,
      this.badge = 'shield'});
  final String id;
  final String titleEn;
  final String titleNl;
  final String descriptionEn;
  final String descriptionNl;
  final int target;
  final AchievementCategory category;
  final bool secret;
  final String badge;

  String get badgeAsset =>
      'assets/images/achievements/$badge${badge.contains('.') ? '' : '.png'}';
}

const achievementCatalog = <AchievementDefinition>[
  AchievementDefinition(
      id: 'hello_little_one',
      titleEn: 'Hello, Little One!',
      titleNl: 'Hallo, Kleintje!',
      descriptionEn: 'Hatch your Starter Egg.',
      descriptionNl: 'Laat je Starter Egg uitkomen.',
      target: 1,
      category: AchievementCategory.starter,
      badge: 'egg'),
  AchievementDefinition(
      id: 'guided_tour',
      titleEn: 'A Little Less Lost',
      titleNl: 'Iets Minder Verdwaald',
      descriptionEn: 'Finish the DragonHaven tutorial.',
      descriptionNl: 'Voltooi de DragonHaven-tutorial.',
      target: 1,
      category: AchievementCategory.starter,
      badge: 'tutorial_tour'),
  AchievementDefinition(
      id: 'first_flight',
      titleEn: 'First Flight',
      titleNl: 'Eerste Vlucht',
      descriptionEn: 'Complete your first Short Adventure.',
      descriptionNl: 'Voltooi je eerste Short Adventure.',
      target: 1,
      category: AchievementCategory.easy,
      badge: 'first_flight'),
  AchievementDefinition(
      id: 'chest_expectations',
      titleEn: 'Chest Expectations',
      titleNl: 'Kistverwachtingen',
      descriptionEn: 'Open your first chest.',
      descriptionNl: 'Open je eerste kist.',
      target: 1,
      category: AchievementCategory.easy,
      badge: 'first_chest'),
  AchievementDefinition(
      id: 'profile_picture_perfect',
      titleEn: 'Profile Picture Perfect',
      titleNl: 'Profielplaatje Perfect',
      descriptionEn:
          'Open your first Portrait Chest. Your account found its good side.',
      descriptionNl:
          'Open je eerste Portrait Chest. Je account heeft zijn beste kant gevonden.',
      target: 1,
      category: AchievementCategory.easy,
      badge: 'portrait_premiere.webp'),
  AchievementDefinition(
      id: 'highly_titled',
      titleEn: 'Highly Titled',
      titleNl: 'Hooggetiteld',
      descriptionEn:
          'Open your first Title Chest. Try not to let it go to your head.',
      descriptionNl:
          'Open je eerste Title Chest. Laat het niet naar je hoofd stijgen.',
      target: 1,
      category: AchievementCategory.easy,
      badge: 'title_unboxed.webp'),
  AchievementDefinition(
      id: 'room_to_roost',
      titleEn: 'Room to Roost',
      titleNl: 'Ruimte om te Rusten',
      descriptionEn: 'Buy your first extra Dragon Tower floor.',
      descriptionNl: 'Koop je eerste extra verdieping in de Dragon Tower.',
      target: 2,
      category: AchievementCategory.easy,
      badge: 'first_floor'),
  AchievementDefinition(
      id: 'feed_furniture',
      titleEn: 'Do Not Feed the Furniture',
      titleNl: 'Voer het Meubilair Niet',
      descriptionEn: 'Place your first furniture item.',
      descriptionNl: 'Plaats je eerste meubelstuk.',
      target: 1,
      category: AchievementCategory.easy,
      badge: 'first_furniture'),
  AchievementDefinition(
      id: 'book_wyrm',
      titleEn: 'Book Wyrm',
      titleNl: 'Boekenwyrm',
      descriptionEn: 'Discover 5 Common dragon families.',
      descriptionNl: 'Ontdek 5 Common-drakenfamilies.',
      target: 5,
      category: AchievementCategory.easy,
      badge: 'common_five'),
  AchievementDefinition(
      id: 'growing_pains',
      titleEn: 'Growing Pains',
      titleNl: 'Groeipijnen',
      descriptionEn: 'Evolve a Hatchling into a Wyrmling.',
      descriptionNl: 'Laat een Hatchling evolueren naar een Wyrmling.',
      target: 1,
      category: AchievementCategory.easy,
      badge: 'first_evolution'),
  AchievementDefinition(
      id: 'not_picking_favorites',
      titleEn: 'Definitely Not Picking Favorites',
      titleNl: 'Zeker Geen Favorieten Kiezen',
      descriptionEn: 'Change your favorite dragon for the first time.',
      descriptionNl: 'Verander voor het eerst je favoriete draak.',
      target: 1,
      category: AchievementCategory.easy,
      badge: 'favorite'),
  AchievementDefinition(
      id: 'halfway_clouds',
      titleEn: 'Halfway to the Clouds',
      titleNl: 'Halverwege de Wolken',
      descriptionEn: 'Build 10 Dragon Tower floors.',
      descriptionNl: 'Bouw 10 verdiepingen in de Dragon Tower.',
      target: 10,
      category: AchievementCategory.challenging,
      badge: 'tower_ten'),
  AchievementDefinition(
      id: 'ascension_day',
      titleEn: 'Ascension Day',
      titleNl: 'Hemelvaartsdag',
      descriptionEn: 'Evolve your first Ascended dragon.',
      descriptionNl: 'Laat je eerste draak Ascended worden.',
      target: 1,
      category: AchievementCategory.challenging,
      badge: 'first_ascension'),
  AchievementDefinition(
      id: 'something_spectral',
      titleEn: 'Something Spectral This Way Comes',
      titleNl: 'Er Komt Iets Spectraals Aan',
      descriptionEn: 'Discover your first Spectral dragon.',
      descriptionNl: 'Ontdek je eerste Spectral-draak.',
      target: 1,
      category: AchievementCategory.challenging,
      badge: 'first_spectral'),
  AchievementDefinition(
      id: 'well_read_scaled',
      titleEn: 'Well Read, Well Scaled',
      titleNl: 'Goed Gelezen, Goed Geschubd',
      descriptionEn: 'Discover 20 Common dragon families.',
      descriptionNl: 'Ontdek 20 Common-drakenfamilies.',
      target: 20,
      category: AchievementCategory.challenging,
      badge: 'common_all'),
  AchievementDefinition(
      id: 'frequent_flyer',
      titleEn: 'Frequent Flyer',
      titleNl: 'Vaste Vlieger',
      descriptionEn: 'Complete 50 Adventures.',
      descriptionNl: 'Voltooi 50 Adventures.',
      target: 50,
      category: AchievementCategory.challenging,
      badge: 'fifty_flights'),
  AchievementDefinition(
      id: 'are_we_there_yet',
      titleEn: 'Are We There Yet?',
      titleNl: 'Zijn We Er Al?',
      descriptionEn: 'Complete 1,000 Adventures.',
      descriptionNl: 'Voltooi 1.000 Adventures.',
      target: 1000,
      category: AchievementCategory.master,
      badge: 'thousand_adventures.webp'),
  AchievementDefinition(
      id: 'full_party',
      titleEn: 'Full Party, Full Send',
      titleNl: 'Volle Groep, Vol Erin',
      descriptionEn: 'Complete a Group Adventure with 4 participants.',
      descriptionNl: 'Voltooi een Group Adventure met 4 deelnemers.',
      target: 1,
      category: AchievementCategory.challenging,
      badge: 'full_group'),
  AchievementDefinition(
      id: 'triple_expertise',
      titleEn: 'Master of All Three',
      titleNl: 'Meester van Alle Drie',
      descriptionEn:
          'Reach 300 Might, 300 Arcana and 300 Spirit on one dragon.',
      descriptionNl: 'Bereik 300 Kracht, 300 Arcana en 300 Geest op één draak.',
      target: 1,
      category: AchievementCategory.master,
      badge: 'triple_mastery'),
  AchievementDefinition(
      id: 'hidden_mastery',
      titleEn: 'Perfectly Balanced',
      titleNl: 'Perfect in Balans',
      descriptionEn: 'Evolve a dragon into its secret Mastery form.',
      descriptionNl: 'Laat een draak evolueren naar zijn geheime Mastery-vorm.',
      target: 1,
      category: AchievementCategory.master,
      secret: true,
      badge: 'mastery_secret.webp'),
  AchievementDefinition(
      id: 'came_crawling_back',
      titleEn: 'Look Who Came Crawling Back',
      titleNl: 'Kijk Wie Terug Kwam Kruipen',
      descriptionEn: 'Receive a visit from a released dragon.',
      descriptionNl: 'Krijg bezoek van een vrijgelaten draak.',
      target: 1,
      category: AchievementCategory.challenging,
      badge: 'first_return'),
  AchievementDefinition(
      id: 'sky_ceiling',
      titleEn: 'The Sky Has a Ceiling After All',
      titleNl: 'De Lucht Heeft Toch een Plafond',
      descriptionEn: 'Reach 20 Dragon Tower floors.',
      descriptionNl: 'Bereik 20 verdiepingen in de Dragon Tower.',
      target: 20,
      category: AchievementCategory.master,
      badge: 'tower_twenty'),
  AchievementDefinition(
      id: 'scale_every_tale',
      titleEn: 'A Scale for Every Tale',
      titleNl: 'Een Schub voor Elk Verhaal',
      descriptionEn: 'Discover 42 dragon families.',
      descriptionNl: 'Ontdek 42 drakenfamilies.',
      target: 42,
      category: AchievementCategory.master,
      badge: 'all_families'),
  AchievementDefinition(
      id: 'ghost_writer',
      titleEn: 'Ghost Writer',
      titleNl: 'Spookschrijver',
      descriptionEn: 'Discover Spectral forms of 10 families.',
      descriptionNl: 'Ontdek Spectral-vormen van 10 families.',
      target: 10,
      category: AchievementCategory.master,
      badge: 'spectral_ten'),
  AchievementDefinition(
      id: 'myth_made_real',
      titleEn: 'Myth Made Real',
      titleNl: 'Mythe Wordt Werkelijk',
      descriptionEn: 'Obtain a Mythical-family dragon.',
      descriptionNl: 'Verkrijg een draak uit de Mythical-familie.',
      target: 1,
      category: AchievementCategory.master,
      badge: 'mythical_family'),
  AchievementDefinition(
      id: 'trial_might_s_plus',
      titleEn: 'Wall? What Wall?',
      titleNl: 'Muur? Welke Muur?',
      descriptionEn: 'Earn an S+ rank in Ruin Breaker.',
      descriptionNl: 'Behaal een S+-rang in Ruinebreker.',
      target: 1,
      category: AchievementCategory.master,
      badge: 'trial_might_s_plus'),
  AchievementDefinition(
      id: 'trial_spirit_s_plus',
      titleEn: 'Crystal-Clear Flying',
      titleNl: 'Kristalhelder Gevlogen',
      descriptionEn: 'Earn an S+ rank in Cavern Flight.',
      descriptionNl: 'Behaal een S+-rang in Grotvlucht.',
      target: 1,
      category: AchievementCategory.master,
      badge: 'trial_spirit_s_plus'),
  AchievementDefinition(
      id: 'trial_arcana_s_plus',
      titleEn: 'Rune and Done',
      titleNl: 'Rune en Klaar',
      descriptionEn: 'Earn an S+ rank in Runeweaver.',
      descriptionNl: 'Behaal een S+-rang in Runenwever.',
      target: 1,
      category: AchievementCategory.master,
      badge: 'trial_arcana_s_plus'),
  AchievementDefinition(
      id: 'winner_chicken_dinner',
      titleEn: 'Winner, Winner, Chicken Dinner',
      titleNl: 'Winner, Winner, Chicken Dinner',
      descriptionEn: 'Hatch the secret Cluckatrice from a Special Egg.',
      descriptionNl: 'Laat de geheime Cluckatrice uit een Speciaal Ei komen.',
      target: 1,
      category: AchievementCategory.master,
      secret: true,
      badge: 'winner_chicken_dinner.webp'),
  AchievementDefinition(
      id: 'probably_fine',
      titleEn: 'This Is Probably Fine',
      titleNl: 'Dit Komt Vast Goed',
      descriptionEn: 'Complete a Sinister Special Adventure.',
      descriptionNl: 'Voltooi een Sinister Special Adventure.',
      target: 1,
      category: AchievementCategory.master,
      secret: true,
      badge: 'sinister_secret'),
];
