enum DragonTrait {
  leafCrown,
  crystalSpines,
  cloudFins,
  emberHorns,
  featherWings,
  moonAntennae,
  tideFrill,
  copperPlates,
  starCrest,
  rainbowRuff,
}

enum DragonRarity { common, uncommon, rare, veryRare, legendary, mythical }

class DragonLineage {
  const DragonLineage({
    required this.id,
    required this.nameEn,
    required this.nameNl,
    required this.affinityCategory,
    required this.primaryColorValue,
    required this.secondaryColorValue,
    required this.accentColorValue,
    required this.trait,
    required this.earthFormEn,
    required this.earthFormNl,
    required this.stormFormEn,
    required this.stormFormNl,
    required this.bondFormEn,
    required this.bondFormNl,
    this.rarity = DragonRarity.common,
    this.primaryRoomId = 'hearth',
    this.secondaryRoomIds = const [],
    this.artSourceId,
    this.secret = false,
  });

  final String id;
  final String nameEn;
  final String nameNl;
  final String affinityCategory;
  final int primaryColorValue;
  final int secondaryColorValue;
  final int accentColorValue;
  final DragonTrait trait;
  final String earthFormEn;
  final String earthFormNl;
  final String stormFormEn;
  final String stormFormNl;
  final String bondFormEn;
  final String bondFormNl;
  final DragonRarity rarity;
  final String primaryRoomId;
  final List<String> secondaryRoomIds;
  final String? artSourceId;
  final bool secret;

  String get spriteId => artSourceId ?? id;

  String name(bool isDutch) => isDutch ? nameNl : nameEn;

  String formName(String path, bool isDutch) => switch (path) {
        'earth' || 'might' => isDutch ? earthFormNl : earthFormEn,
        'storm' || 'arcana' => isDutch ? stormFormNl : stormFormEn,
        'bond' || 'spirit' => isDutch ? bondFormNl : bondFormEn,
        'mastery' => '${name(isDutch)} Mastery',
        _ => name(isDutch),
      };

  String rarityName(bool isDutch) => switch (rarity) {
        DragonRarity.common => isDutch ? 'Gewoon' : 'Common',
        DragonRarity.uncommon => isDutch ? 'Ongewoon' : 'Uncommon',
        DragonRarity.rare => isDutch ? 'Zeldzaam' : 'Rare',
        DragonRarity.veryRare => isDutch ? 'Zeer zeldzaam' : 'Very Rare',
        DragonRarity.legendary => isDutch ? 'Legendarisch' : 'Legendary',
        DragonRarity.mythical => isDutch ? 'Mythisch' : 'Mythical',
      };
}

const dragonLineages = <DragonLineage>[
  DragonLineage(
    id: 'mossprout',
    nameEn: 'Mossprout',
    nameNl: 'Mosspruit',
    affinityCategory: 'earthlight',
    primaryColorValue: 0xFF3F8F69,
    secondaryColorValue: 0xFFA9E5B2,
    accentColorValue: 0xFFFFD45C,
    trait: DragonTrait.leafCrown,
    earthFormEn: 'Ancient Groveback',
    earthFormNl: 'Oude Woudrug',
    stormFormEn: 'Tempest Vinewing',
    stormFormNl: 'Stormrankvleugel',
    bondFormEn: 'Hearthgarden Keeper',
    bondFormNl: 'Haardtuinwachter',
  ),
  DragonLineage(
    id: 'crystalwhisk',
    nameEn: 'Crystalwhisk',
    nameNl: 'Kristalsnor',
    affinityCategory: 'earthlight',
    primaryColorValue: 0xFF6D5BD0,
    secondaryColorValue: 0xFFBCEBFF,
    accentColorValue: 0xFFFFC857,
    trait: DragonTrait.crystalSpines,
    earthFormEn: 'Quartz Mountainclaw',
    earthFormNl: 'Kwartsbergklauw',
    stormFormEn: 'Prism Thundercrest',
    stormFormNl: 'Prismadonderkam',
    bondFormEn: 'Crystal Heartseer',
    bondFormNl: 'Kristallen Hartziener',
  ),
  DragonLineage(
    id: 'dustglimmer',
    nameEn: 'Dustglimmer',
    nameNl: 'Stofglans',
    affinityCategory: 'earthlight',
    primaryColorValue: 0xFFC08B5A,
    secondaryColorValue: 0xFFFFE8B6,
    accentColorValue: 0xFF72D8C1,
    trait: DragonTrait.cloudFins,
    earthFormEn: 'Golden Duneprowler',
    earthFormNl: 'Gouden Duinsluiper',
    stormFormEn: 'Whirling Sunstorm',
    stormFormNl: 'Wervelende Zonnestorm',
    bondFormEn: 'Softlight Denkeeper',
    bondFormNl: 'Zachtlicht Holbewaker',
  ),
  DragonLineage(
    id: 'gleamclaw',
    nameEn: 'Gleamclaw',
    nameNl: 'Glansklauw',
    affinityCategory: 'earthlight',
    primaryColorValue: 0xFF3E7EAA,
    secondaryColorValue: 0xFFF2FAFF,
    accentColorValue: 0xFFEE7BA7,
    trait: DragonTrait.starCrest,
    earthFormEn: 'Mirrorstone Sentinel',
    earthFormNl: 'Spiegelsteenwachter',
    stormFormEn: 'Skyglass Streak',
    stormFormNl: 'Hemelglasflits',
    bondFormEn: 'Brightroom Guardian',
    bondFormNl: 'Lichtkamerbeschermer',
  ),
  DragonLineage(
    id: 'emberbun',
    nameEn: 'Emberbun',
    nameNl: 'Gloedjong',
    affinityCategory: 'ember',
    primaryColorValue: 0xFFD65535,
    secondaryColorValue: 0xFFFFB85C,
    accentColorValue: 0xFF5D315D,
    trait: DragonTrait.emberHorns,
    earthFormEn: 'Magma Ovenback',
    earthFormNl: 'Magma-ovenrug',
    stormFormEn: 'Wildfire Skydancer',
    stormFormNl: 'Wildvuurhemeldanser',
    bondFormEn: 'Everwarm Hearthheart',
    bondFormNl: 'Eeuwarm Haardhart',
  ),
  DragonLineage(
    id: 'copperflame',
    nameEn: 'Copperflame',
    nameNl: 'Kopervlam',
    affinityCategory: 'ember',
    primaryColorValue: 0xFF9C572F,
    secondaryColorValue: 0xFFE7A45C,
    accentColorValue: 0xFF76D8D0,
    trait: DragonTrait.copperPlates,
    earthFormEn: 'Bronze Rootforger',
    earthFormNl: 'Bronzen Wortelsmid',
    stormFormEn: 'Copperbolt Wyvern',
    stormFormNl: 'Koperbliksemwyvern',
    bondFormEn: 'Kindleforge Companion',
    bondFormNl: 'Vonksmidkameraad',
  ),
  DragonLineage(
    id: 'spicewing',
    nameEn: 'Spicewing',
    nameNl: 'Kruidvleugel',
    affinityCategory: 'ember',
    primaryColorValue: 0xFFB03A64,
    secondaryColorValue: 0xFFF4A261,
    accentColorValue: 0xFFB9E769,
    trait: DragonTrait.featherWings,
    earthFormEn: 'Saffron Grovefeather',
    earthFormNl: 'Saffraanwoudveer',
    stormFormEn: 'Pepperwind Raptor',
    stormFormNl: 'Peperwindjager',
    bondFormEn: 'Feastday Heartwing',
    bondFormNl: 'Feestdaghartvleugel',
  ),
  DragonLineage(
    id: 'bubblefin',
    nameEn: 'Bubblefin',
    nameNl: 'Bubbelfin',
    affinityCategory: 'tide',
    primaryColorValue: 0xFF2C9FC5,
    secondaryColorValue: 0xFFB9F1F4,
    accentColorValue: 0xFFFF8FB1,
    trait: DragonTrait.tideFrill,
    earthFormEn: 'Riverstone Rippleback',
    earthFormNl: 'Riviersteenrimpelrug',
    stormFormEn: 'Foamstorm Sailfin',
    stormFormNl: 'Schuimstormzeilvin',
    bondFormEn: 'Bathhouse Bubbleheart',
    bondFormNl: 'Badhuisbubbelhart',
  ),
  DragonLineage(
    id: 'linencloud',
    nameEn: 'Linencloud',
    nameNl: 'Linnenwolk',
    affinityCategory: 'tide',
    primaryColorValue: 0xFF7189BF,
    secondaryColorValue: 0xFFF8F3E7,
    accentColorValue: 0xFFF1C75B,
    trait: DragonTrait.cloudFins,
    earthFormEn: 'Cottonwood Dreamer',
    earthFormNl: 'Katoenwouddromer',
    stormFormEn: 'White Squall Glider',
    stormFormNl: 'Witte Windvlaagzwever',
    bondFormEn: 'Blanketfort Guardian',
    bondFormNl: 'Dekenfortbeschermer',
  ),
  DragonLineage(
    id: 'tidescale',
    nameEn: 'Tidescale',
    nameNl: 'Getijdenschaal',
    affinityCategory: 'tide',
    primaryColorValue: 0xFF176B87,
    secondaryColorValue: 0xFF61D6C4,
    accentColorValue: 0xFFFFD166,
    trait: DragonTrait.tideFrill,
    earthFormEn: 'Deepreef Mossjaw',
    earthFormNl: 'Diep rifmoskaak',
    stormFormEn: 'Riptide Thunderfin',
    stormFormNl: 'Springtij-dondervin',
    bondFormEn: 'Harborlight Protector',
    bondFormNl: 'Havenlichtbeschermer',
  ),
  DragonLineage(
    id: 'clockskip',
    nameEn: 'Clockskip',
    nameNl: 'Kloksprong',
    affinityCategory: 'tempest',
    primaryColorValue: 0xFF7559A8,
    secondaryColorValue: 0xFFE3C6FF,
    accentColorValue: 0xFFF0B84B,
    trait: DragonTrait.copperPlates,
    earthFormEn: 'Rootclock Behemoth',
    earthFormNl: 'Wortelklokreus',
    stormFormEn: 'Secondhand Swiftwing',
    stormFormNl: 'Secondewijzersnelvleugel',
    bondFormEn: 'Daykeeper Companion',
    bondFormNl: 'Dagwachterkameraad',
  ),
  DragonLineage(
    id: 'galeear',
    nameEn: 'Galeear',
    nameNl: 'Windoor',
    affinityCategory: 'tempest',
    primaryColorValue: 0xFF4D82C4,
    secondaryColorValue: 0xFFC9E9FF,
    accentColorValue: 0xFFFFD35A,
    trait: DragonTrait.featherWings,
    earthFormEn: 'Hillwind Longhorn',
    earthFormNl: 'Heuvelwindlanghoorn',
    stormFormEn: 'Jetstream Skyhare',
    stormFormNl: 'Straalstroomhemelhaas',
    bondFormEn: 'Morningcall Friend',
    bondFormNl: 'Ochtendroepvriend',
  ),
  DragonLineage(
    id: 'thunderpuff',
    nameEn: 'Thunderpuff',
    nameNl: 'Donderpluis',
    affinityCategory: 'tempest',
    primaryColorValue: 0xFF454B8C,
    secondaryColorValue: 0xFFB8C8FF,
    accentColorValue: 0xFFFFE066,
    trait: DragonTrait.cloudFins,
    earthFormEn: 'Rainroot Cloudbear',
    earthFormNl: 'Regenwortelwolkenbeer',
    stormFormEn: 'Thunderhead Roarer',
    stormFormNl: 'Donderkopbruller',
    bondFormEn: 'Cozyweather Keeper',
    bondFormNl: 'Knusweerwachter',
  ),
  DragonLineage(
    id: 'dreammoth',
    nameEn: 'Dreammoth',
    nameNl: 'Droommot',
    affinityCategory: 'moon',
    primaryColorValue: 0xFF8066B8,
    secondaryColorValue: 0xFFF0D7FF,
    accentColorValue: 0xFF77D8C6,
    trait: DragonTrait.moonAntennae,
    earthFormEn: 'Moonpetal Sleeper',
    earthFormNl: 'Maanbloemslaper',
    stormFormEn: 'Nightwind Silkmoth',
    stormFormNl: 'Nachtwindzijdenmot',
    bondFormEn: 'Dreamnest Comforter',
    bondFormNl: 'Droomnesttrooster',
  ),
  DragonLineage(
    id: 'dewhorn',
    nameEn: 'Dewhorn',
    nameNl: 'Dauwhoorn',
    affinityCategory: 'moon',
    primaryColorValue: 0xFF4BAE92,
    secondaryColorValue: 0xFFCFF9E8,
    accentColorValue: 0xFFFFC66E,
    trait: DragonTrait.leafCrown,
    earthFormEn: 'Meadow Crownstag',
    earthFormNl: 'Weidekroonhert',
    stormFormEn: 'Dawnmist Windhorn',
    stormFormNl: 'Dageraadmisthoorn',
    bondFormEn: 'Gentlegrove Healer',
    bondFormNl: 'Zachtwoudheler',
  ),
  DragonLineage(
    id: 'quietstar',
    nameEn: 'Quietstar',
    nameNl: 'Stilster',
    affinityCategory: 'moon',
    primaryColorValue: 0xFF343D78,
    secondaryColorValue: 0xFFAFC7FF,
    accentColorValue: 0xFFFFE999,
    trait: DragonTrait.starCrest,
    earthFormEn: 'Stillstone Stargazer',
    earthFormNl: 'Stilsteensterrenkijker',
    stormFormEn: 'Silent Cometwing',
    stormFormNl: 'Stille Komeetvleugel',
    bondFormEn: 'Wishlight Listener',
    bondFormNl: 'Wenslichtluisteraar',
  ),
  DragonLineage(
    id: 'heartwing',
    nameEn: 'Heartwing',
    nameNl: 'Hartvleugel',
    affinityCategory: 'heart',
    primaryColorValue: 0xFFC44E79,
    secondaryColorValue: 0xFFFFB5C9,
    accentColorValue: 0xFFFFD25B,
    trait: DragonTrait.featherWings,
    earthFormEn: 'Rosewood Heartguard',
    earthFormNl: 'Rozenhouthartwacht',
    stormFormEn: 'Valentine Stormswift',
    stormFormNl: 'Hartstormsnelle',
    bondFormEn: 'Great Kinship Dragon',
    bondFormNl: 'Grote Verbondsdraak',
  ),
  DragonLineage(
    id: 'twinflare',
    nameEn: 'Twinflare',
    nameNl: 'Tweelingvlam',
    affinityCategory: 'heart',
    primaryColorValue: 0xFF9B4CC0,
    secondaryColorValue: 0xFFFF805D,
    accentColorValue: 0xFF6FE0C1,
    trait: DragonTrait.emberHorns,
    earthFormEn: 'Doublebloom Basilisk',
    earthFormNl: 'Dubbelbloembasilisk',
    stormFormEn: 'Dancing Dualflame',
    stormFormNl: 'Dansende Dubbelvlam',
    bondFormEn: 'Twoheart Housewarden',
    bondFormNl: 'Tweehartenhuiswachter',
  ),
  DragonLineage(
    id: 'rainbowruff',
    nameEn: 'Rainbowruff',
    nameNl: 'Regenboogkam',
    affinityCategory: 'heart',
    primaryColorValue: 0xFF4E67C8,
    secondaryColorValue: 0xFF62D5B2,
    accentColorValue: 0xFFFF7E9C,
    trait: DragonTrait.rainbowRuff,
    earthFormEn: 'Manyflower Ridgeback',
    earthFormNl: 'Veelbloemenrug',
    stormFormEn: 'Aurora Ribbonwing',
    stormFormNl: 'Auroralintvleugel',
    bondFormEn: 'Festival Hearthdragon',
    bondFormNl: 'Feesthaarddraak',
  ),
  DragonLineage(
    id: 'harmonytail',
    nameEn: 'Harmonytail',
    nameNl: 'Harmoniestaart',
    affinityCategory: 'heart',
    primaryColorValue: 0xFF3E8D9A,
    secondaryColorValue: 0xFFD9B6FF,
    accentColorValue: 0xFFFFD36A,
    trait: DragonTrait.moonAntennae,
    earthFormEn: 'Choirgrove Serpent',
    earthFormNl: 'Koorwoudslang',
    stormFormEn: 'Songstorm Skydrake',
    stormFormNl: 'Zangstormhemeldraak',
    bondFormEn: 'Homechorus Guardian',
    bondFormNl: 'Thuiskoorgardiaan',
  ),
  DragonLineage(
    id: 'bramblequill',
    nameEn: 'Bramblequill',
    nameNl: 'Braamveer',
    affinityCategory: 'wildwood',
    primaryColorValue: 0xFF4F7D4A,
    secondaryColorValue: 0xFFD3A95C,
    accentColorValue: 0xFFE86684,
    trait: DragonTrait.leafCrown,
    earthFormEn: 'Thornwall Colossus',
    earthFormNl: 'Doornwalreus',
    stormFormEn: 'Briarbolt Skyrake',
    stormFormNl: 'Braambliksemvleugel',
    bondFormEn: 'Rosebark Warden',
    bondFormNl: 'Rozenbastwachter',
    rarity: DragonRarity.uncommon,
    primaryRoomId: 'garden',
    secondaryRoomIds: ['hearth', 'loft'],
  ),
  DragonLineage(
    id: 'cinderlynx',
    nameEn: 'Cinderlynx',
    nameNl: 'Sintelsluiper',
    affinityCategory: 'ember',
    primaryColorValue: 0xFF8D2F26,
    secondaryColorValue: 0xFFFF8F3D,
    accentColorValue: 0xFF34213F,
    trait: DragonTrait.emberHorns,
    earthFormEn: 'Furnace Prowler',
    earthFormNl: 'Ovensluiper',
    stormFormEn: 'Ashstorm Hunter',
    stormFormNl: 'Asstormjager',
    bondFormEn: 'Kindleheart Sentinel',
    bondFormNl: 'Vonkenhartwachter',
    rarity: DragonRarity.uncommon,
    primaryRoomId: 'sunforge',
    secondaryRoomIds: ['hearth'],
  ),
  DragonLineage(
    id: 'mistmantle',
    nameEn: 'Mistmantle',
    nameNl: 'Mistmantel',
    affinityCategory: 'tide',
    primaryColorValue: 0xFF427C91,
    secondaryColorValue: 0xFFD8F1EE,
    accentColorValue: 0xFF8F78C9,
    trait: DragonTrait.tideFrill,
    earthFormEn: 'Fogbank Leviathan',
    earthFormNl: 'Mistbankleviathan',
    stormFormEn: 'Rainveil Glider',
    stormFormNl: 'Regensluierzwever',
    bondFormEn: 'Harborhush Guardian',
    bondFormNl: 'Havenstiltebewaker',
    rarity: DragonRarity.uncommon,
    primaryRoomId: 'tidal_library',
    secondaryRoomIds: ['cloud'],
  ),
  DragonLineage(
    id: 'runehopper',
    nameEn: 'Runehopper',
    nameNl: 'Runenspringer',
    affinityCategory: 'arcane',
    primaryColorValue: 0xFF674AA8,
    secondaryColorValue: 0xFFBDE8FF,
    accentColorValue: 0xFFFFCF5A,
    trait: DragonTrait.starCrest,
    earthFormEn: 'Glyphstone Titan',
    earthFormNl: 'Runensteentitaan',
    stormFormEn: 'Sigilflash Wyvern',
    stormFormNl: 'Zegellichtwyvern',
    bondFormEn: 'Lorekeeper Familiar',
    bondFormNl: 'Kennishoeder',
    rarity: DragonRarity.uncommon,
    primaryRoomId: 'crystal',
    secondaryRoomIds: ['tidal_library', 'loft'],
  ),
  DragonLineage(
    id: 'petaldrift',
    nameEn: 'Petaldrift',
    nameNl: 'Bloesemzweef',
    affinityCategory: 'bloom',
    primaryColorValue: 0xFFD86F9D,
    secondaryColorValue: 0xFFFFDCE8,
    accentColorValue: 0xFF69B983,
    trait: DragonTrait.featherWings,
    earthFormEn: 'Bloomroot Matriarch',
    earthFormNl: 'Bloesemwortelmatriarch',
    stormFormEn: 'Petal Gale',
    stormFormNl: 'Bloesemstorm',
    bondFormEn: 'Springhome Keeper',
    bondFormNl: 'Lentehuiswachter',
    rarity: DragonRarity.uncommon,
    primaryRoomId: 'garden',
    secondaryRoomIds: ['hearth'],
  ),
  DragonLineage(
    id: 'ironwhistle',
    nameEn: 'Ironwhistle',
    nameNl: 'IJzerfluit',
    affinityCategory: 'clockwork',
    primaryColorValue: 0xFF66707A,
    secondaryColorValue: 0xFFC78A45,
    accentColorValue: 0xFF63D1C8,
    trait: DragonTrait.copperPlates,
    earthFormEn: 'Gearvault Juggernaut',
    earthFormNl: 'Tandwielkluisreus',
    stormFormEn: 'Steamshriek Racer',
    stormFormNl: 'Stoomfluitracer',
    bondFormEn: 'Workshop Companion',
    bondFormNl: 'Werkplaatskameraad',
    rarity: DragonRarity.uncommon,
    primaryRoomId: 'loft',
    secondaryRoomIds: ['sunforge'],
  ),
  DragonLineage(
    id: 'frostfable',
    nameEn: 'Frostfable',
    nameNl: 'Vorstfabel',
    affinityCategory: 'frost',
    primaryColorValue: 0xFF5E8EC2,
    secondaryColorValue: 0xFFEAF9FF,
    accentColorValue: 0xFFB684DF,
    trait: DragonTrait.crystalSpines,
    earthFormEn: 'Glacier Storykeeper',
    earthFormNl: 'Gletsjerverhaalhoeder',
    stormFormEn: 'Blizzard Quillwing',
    stormFormNl: 'Sneeuwstormveervleugel',
    bondFormEn: 'Wintertale Guardian',
    bondFormNl: 'Winterverhaalwachter',
    rarity: DragonRarity.uncommon,
    primaryRoomId: 'crystal',
    secondaryRoomIds: ['tidal_library'],
  ),
  DragonLineage(
    id: 'sunmuzzle',
    nameEn: 'Sunmuzzle',
    nameNl: 'Zonnesnuit',
    affinityCategory: 'solar',
    primaryColorValue: 0xFFE3A12F,
    secondaryColorValue: 0xFFFFE7A0,
    accentColorValue: 0xFFCC596C,
    trait: DragonTrait.emberHorns,
    earthFormEn: 'Daybreak Liondrake',
    earthFormNl: 'Dageraadleeuwdraak',
    stormFormEn: 'Solarflare Runner',
    stormFormNl: 'Zonnevlamrenner',
    bondFormEn: 'Warmthkeeper',
    bondFormNl: 'Warmtehoeder',
    rarity: DragonRarity.uncommon,
    primaryRoomId: 'sunforge',
    secondaryRoomIds: ['garden'],
  ),
  DragonLineage(
    id: 'echofern',
    nameEn: 'Echofern',
    nameNl: 'Echovaren',
    affinityCategory: 'wildwood',
    primaryColorValue: 0xFF337B64,
    secondaryColorValue: 0xFF9DDCB8,
    accentColorValue: 0xFF6B5BAE,
    trait: DragonTrait.moonAntennae,
    earthFormEn: 'Deepgrove Echo',
    earthFormNl: 'Diepwoudecho',
    stormFormEn: 'Canopy Songwing',
    stormFormNl: 'Kruinenzangvleugel',
    bondFormEn: 'Fernhollow Friend',
    bondFormNl: 'Varenholvriend',
    rarity: DragonRarity.uncommon,
    primaryRoomId: 'garden',
    secondaryRoomIds: ['tidal_library'],
  ),
  DragonLineage(
    id: 'velvetvolt',
    nameEn: 'Velvetvolt',
    nameNl: 'Fluweelvonk',
    affinityCategory: 'tempest',
    primaryColorValue: 0xFF4C3B86,
    secondaryColorValue: 0xFFB8A9E8,
    accentColorValue: 0xFFFFE65A,
    trait: DragonTrait.cloudFins,
    earthFormEn: 'Stormplush Behemoth',
    earthFormNl: 'Stormpluchekolos',
    stormFormEn: 'Velvet Thunderbolt',
    stormFormNl: 'Fluwelendonder',
    bondFormEn: 'Rainyday Comforter',
    bondFormNl: 'Regendagtrooster',
    rarity: DragonRarity.uncommon,
    primaryRoomId: 'cloud',
    secondaryRoomIds: ['hearth', 'loft'],
  ),
  DragonLineage(
    id: 'auroracrown',
    nameEn: 'Auroracrown',
    nameNl: 'Aurorakroon',
    affinityCategory: 'aurora',
    primaryColorValue: 0xFF3AA6A1,
    secondaryColorValue: 0xFF8E73D1,
    accentColorValue: 0xFFFF78AB,
    trait: DragonTrait.rainbowRuff,
    earthFormEn: 'Northern Crownbeast',
    earthFormNl: 'Noorderkroonbeest',
    stormFormEn: 'Skyweaver Sovereign',
    stormFormNl: 'Hemelwevervorst',
    bondFormEn: 'Aurora Hearthqueen',
    bondFormNl: 'Aurorahaardkoningin',
    rarity: DragonRarity.rare,
    primaryRoomId: 'cloud',
    secondaryRoomIds: ['crystal'],
  ),
  DragonLineage(
    id: 'voidbloom',
    nameEn: 'Voidbloom',
    nameNl: 'Leegtebloei',
    affinityCategory: 'void',
    primaryColorValue: 0xFF261F4B,
    secondaryColorValue: 0xFF9B74D5,
    accentColorValue: 0xFF69E0C1,
    trait: DragonTrait.moonAntennae,
    earthFormEn: 'Abyssal Rootlord',
    earthFormNl: 'Afgrondwortelheer',
    stormFormEn: 'Nullstar Reaver',
    stormFormNl: 'Nulsterjager',
    bondFormEn: 'Quiet Between Stars',
    bondFormNl: 'Stilte Tussen Sterren',
    rarity: DragonRarity.rare,
    primaryRoomId: 'crystal',
    secondaryRoomIds: ['cloud'],
  ),
  DragonLineage(
    id: 'coraloracle',
    nameEn: 'Coraloracle',
    nameNl: 'Koraalorakel',
    affinityCategory: 'tide',
    primaryColorValue: 0xFFDF6D73,
    secondaryColorValue: 0xFF5ED1C6,
    accentColorValue: 0xFFFFD380,
    trait: DragonTrait.tideFrill,
    earthFormEn: 'Reefprophet Ancient',
    earthFormNl: 'Rifprofeetoude',
    stormFormEn: 'Typhoon Seer',
    stormFormNl: 'Tyfoonziener',
    bondFormEn: 'Tidepool Oracle',
    bondFormNl: 'Getijdenorakel',
    rarity: DragonRarity.rare,
    primaryRoomId: 'tidal_library',
    secondaryRoomIds: ['garden'],
  ),
  DragonLineage(
    id: 'meteorhide',
    nameEn: 'Meteorhide',
    nameNl: 'Meteoorhuid',
    affinityCategory: 'cosmic',
    primaryColorValue: 0xFF5A506F,
    secondaryColorValue: 0xFFE58B55,
    accentColorValue: 0xFF8DE7FF,
    trait: DragonTrait.crystalSpines,
    earthFormEn: 'Craterback Worldshaker',
    earthFormNl: 'Kraterrugwereldschudder',
    stormFormEn: 'Cometfall Devastator',
    stormFormNl: 'Komeetvalverwoester',
    bondFormEn: 'Starstone Protector',
    bondFormNl: 'Stersteenbeschermer',
    rarity: DragonRarity.rare,
    primaryRoomId: 'sunforge',
    secondaryRoomIds: ['crystal'],
  ),
  DragonLineage(
    id: 'temporalark',
    nameEn: 'Temporalark',
    nameNl: 'Tijdboog',
    affinityCategory: 'time',
    primaryColorValue: 0xFF7757AA,
    secondaryColorValue: 0xFFE0C86C,
    accentColorValue: 0xFF66D5D0,
    trait: DragonTrait.copperPlates,
    earthFormEn: 'Epoch Bastion',
    earthFormNl: 'Tijdperkbolwerk',
    stormFormEn: 'Hourglass Tempest',
    stormFormNl: 'Zandloperstorm',
    bondFormEn: 'Memory Archivist',
    bondFormNl: 'Herinneringsarchivaris',
    rarity: DragonRarity.rare,
    primaryRoomId: 'loft',
    secondaryRoomIds: ['tidal_library'],
  ),
  DragonLineage(
    id: 'opalchimera',
    nameEn: 'Opalchimera',
    nameNl: 'Opaalchimera',
    affinityCategory: 'prism',
    primaryColorValue: 0xFF7D72BE,
    secondaryColorValue: 0xFFFFC8D6,
    accentColorValue: 0xFF75D9A6,
    trait: DragonTrait.rainbowRuff,
    earthFormEn: 'Opaline Manyhorn',
    earthFormNl: 'Opaalveelhoorn',
    stormFormEn: 'Refraction Chimera',
    stormFormNl: 'Brekingchimera',
    bondFormEn: 'Gemheart Wonder',
    bondFormNl: 'Edelsteenhartwonder',
    rarity: DragonRarity.rare,
    primaryRoomId: 'crystal',
    secondaryRoomIds: ['garden', 'cloud'],
  ),
  DragonLineage(
    id: 'eclipseantler',
    nameEn: 'Eclipseantler',
    nameNl: 'Eclipsgewei',
    affinityCategory: 'eclipse',
    primaryColorValue: 0xFF222747,
    secondaryColorValue: 0xFFE6B34A,
    accentColorValue: 0xFF9D65C5,
    trait: DragonTrait.starCrest,
    earthFormEn: 'Umbral Crownstag',
    earthFormNl: 'Schaduwkroonhert',
    stormFormEn: 'Totality Nightwing',
    stormFormNl: 'Totaliteitsnachtvleugel',
    bondFormEn: 'Twilight Gatekeeper',
    bondFormNl: 'Schemerpoortwachter',
    rarity: DragonRarity.veryRare,
    primaryRoomId: 'cloud',
    secondaryRoomIds: ['crystal'],
  ),
  DragonLineage(
    id: 'worldroot',
    nameEn: 'Worldroot',
    nameNl: 'Wereldwortel',
    affinityCategory: 'primordial',
    primaryColorValue: 0xFF365B3E,
    secondaryColorValue: 0xFF9C793C,
    accentColorValue: 0xFF69CAA2,
    trait: DragonTrait.leafCrown,
    earthFormEn: 'Continental Groveback',
    earthFormNl: 'Continentale Woudrug',
    stormFormEn: 'Canopy Worldstorm',
    stormFormNl: 'Kruinenwereldstorm',
    bondFormEn: 'First Garden Guardian',
    bondFormNl: 'Eerste Tuinwachter',
    rarity: DragonRarity.veryRare,
    primaryRoomId: 'garden',
    secondaryRoomIds: ['hearth'],
  ),
  DragonLineage(
    id: 'seraphscale',
    nameEn: 'Seraphscale',
    nameNl: 'Serafijnschaal',
    affinityCategory: 'celestial',
    primaryColorValue: 0xFFF3E2B2,
    secondaryColorValue: 0xFFB6D9FF,
    accentColorValue: 0xFFFFD35F,
    trait: DragonTrait.featherWings,
    earthFormEn: 'Haloed Bastion',
    earthFormNl: 'Heiligenkringbolwerk',
    stormFormEn: 'Heavensong Archwing',
    stormFormNl: 'Hemelzangvleugel',
    bondFormEn: 'Grace of the Haven',
    bondFormNl: 'Genade van de Haven',
    rarity: DragonRarity.veryRare,
    primaryRoomId: 'hearth',
    secondaryRoomIds: ['cloud', 'sunforge'],
  ),
  DragonLineage(
    id: 'starforged',
    nameEn: 'Starforged',
    nameNl: 'Stergesmeed',
    affinityCategory: 'cosmic',
    primaryColorValue: 0xFF263268,
    secondaryColorValue: 0xFFC3D8FF,
    accentColorValue: 0xFFFFB64D,
    trait: DragonTrait.starCrest,
    earthFormEn: 'Constellation Titan',
    earthFormNl: 'Sterrenbeeldtitaan',
    stormFormEn: 'Supernova Sovereign',
    stormFormNl: 'Supernovavorst',
    bondFormEn: 'Northstar Guardian',
    bondFormNl: 'Poolsterwachter',
    rarity: DragonRarity.legendary,
    primaryRoomId: 'sunforge',
    secondaryRoomIds: ['cloud', 'crystal'],
  ),
  DragonLineage(
    id: 'leviathanecho',
    nameEn: 'Leviathanecho',
    nameNl: 'Leviathanecho',
    affinityCategory: 'abyssal',
    primaryColorValue: 0xFF123C5A,
    secondaryColorValue: 0xFF2ABFB3,
    accentColorValue: 0xFFA96BDD,
    trait: DragonTrait.tideFrill,
    earthFormEn: 'Abyssfloor Monarch',
    earthFormNl: 'Afgrondvorst',
    stormFormEn: 'Worldtide Leviathan',
    stormFormNl: 'Wereldtijleviathan',
    bondFormEn: 'Ocean Memory',
    bondFormNl: 'Oceaanherinnering',
    rarity: DragonRarity.legendary,
    primaryRoomId: 'tidal_library',
    secondaryRoomIds: ['crystal'],
  ),
  DragonLineage(
    id: 'everwyrm',
    nameEn: 'Everwyrm',
    nameNl: 'Eeuwwyrm',
    affinityCategory: 'creation',
    primaryColorValue: 0xFFEEE0A2,
    secondaryColorValue: 0xFF6C63B8,
    accentColorValue: 0xFF5AD6B3,
    trait: DragonTrait.rainbowRuff,
    earthFormEn: 'Havenmaker Eternal',
    earthFormNl: 'Eeuwige Havenmaker',
    stormFormEn: 'Beginning Without End',
    stormFormNl: 'Begin Zonder Einde',
    bondFormEn: 'Heart of DragonHaven',
    bondFormNl: 'Hart van DragonHaven',
    rarity: DragonRarity.mythical,
    primaryRoomId: 'hearth',
    secondaryRoomIds: ['crystal', 'cloud'],
  ),
  DragonLineage(
    id: 'cluckatrice',
    nameEn: 'Cluckatrice',
    nameNl: 'Cluckatrice',
    affinityCategory: 'dawn',
    primaryColorValue: 0xFFF2DFC1,
    secondaryColorValue: 0xFFC94B3C,
    accentColorValue: 0xFFFFC857,
    trait: DragonTrait.featherWings,
    earthFormEn: 'Roostguard Colossus',
    earthFormNl: 'Nestwachtkolos',
    stormFormEn: 'Dawnspell Plume',
    stormFormNl: 'Dageraadsveer',
    bondFormEn: 'Hearthflock Herald',
    bondFormNl: 'Haardverenheraut',
    rarity: DragonRarity.mythical,
    primaryRoomId: 'garden',
    secondaryRoomIds: ['hearth', 'sunforge'],
    secret: true,
  ),
];

final List<DragonLineage> standardDragonLineages =
    List.unmodifiable(dragonLineages.where((lineage) => !lineage.secret));

final Map<String, DragonLineage> _dragonLineagesById =
    Map<String, DragonLineage>.unmodifiable({
  for (final lineage in dragonLineages) lineage.id: lineage,
});

DragonLineage dragonLineageById(String? id) =>
    _dragonLineagesById[id] ?? dragonLineages.first;
