/// Protocol identities shared by the client journal and server evaluator.
/// No score, reward amount, entitlement or unverified grant is accepted here.
abstract final class GameCommandSchema {
  static const keys = <String, Set<String>>{
    'refresh': {},
    'invite_pair_adventure': {'keeperCode', 'dragonId'},
    'accept_pair_adventure': {'adventureId', 'dragonId'},
    'decline_pair_adventure': {'adventureId'},
    'start_pair_adventure': {'adventureId'},
    'cancel_pair_adventure': {'adventureId'},
    'create_group_adventure': {'adventureId', 'dragonId'},
    'join_group_adventure': {'lobbyId', 'dragonId'},
    'leave_group_adventure': {'lobbyId'},
    'remove_group_adventure_member': {'lobbyId', 'memberId'},
    'claim_group_reward': {'lobbyId'},
    'claim_pair_reward': {'adventureId'},
    'claim_podium_prize': {'prizeId'},
    'start_trial': {'offerId', 'dragonId'},
    'checkpoint_trial': {'attemptId', 'inputs', 'elapsedMs', 'finish'},
    'cancel_trial': {'attemptId'},
    'start_school': {'gameId', 'dragonIds', 'mentorId'},
    'finish_school': {'attemptId', 'inputs'},
    'cancel_school': {'attemptId'},
    'graduate_school': {'dragonId'},
    'purchase_portrait_chest': {},
    'purchase_title_chest': {},
    'purchase_music_chest': {},
    'purchase_furniture': {'catalogId'},
    'purchase_relic': {'relic'},
    'open_chests': {'tier', 'count'},
    'open_special_chests': {'catalogId', 'count'},
    'use_relic': {'relic', 'dragonId'},
    'use_astral_lens': {'eggId'},
    'tag_egg': {'eggId', 'tagged'},
    'return_egg': {'eggId', 'sinisterConfirmed'},
    'craft_altar_relic': {'relic'},
    'use_altar_relic': {'relic', 'eggId'},
    'use_chronoshard': {'reductionPercent'},
    'use_wayfinder': {'kind', 'replaceAdventureId'},
    'equip_twinstar': {'dragonId'},
    'equip_relic': {'relic', 'dragonId'},
    'activate_egg': {'eggId'},
    'hatch_egg': {'eggId'},
    'name_dragon': {'dragonId', 'name'},
    'set_dragon_highlight': {'dragonId', 'focus', 'highlighted'},
    'set_favorite_dragon': {'dragonId'},
    'evolve_dragon': {'dragonId'},
    'buy_starlight_treat': {'dragonId'},
    'release_dragon': {'dragonId'},
    'start_adventure': {'adventureId', 'dragonId'},
    'dismiss_adventure': {'adventureId'},
    'claim_adventure': {'runId'},
    'abort_adventure': {'runId'},
    'dismiss_trial': {'offerId'},
    'claim_constellation': {},
    'unlock_room': {'roomId'},
    'build_floor': {'roomId'},
    'repair_floor': {'index'},
    'upgrade_ward': {},
    'place_house_item': {'itemId', 'roomId', 'x', 'y'},
    'move_house_item': {'itemId', 'x', 'y'},
    'remove_house_item': {'itemId'},
    'reorder_tower_floor': {'oldIndex', 'newIndex'},
    'set_dragon_roaming': {'dragonId', 'enabled'},
    'clear_tower_floor': {'index'},
    'select_portrait': {'catalogId'},
    'select_title': {'catalogId'},
    'select_badge': {'catalogId'},
    'select_frame': {'catalogId'},
    'complete_presentation': {'presentationId'},
    'call_dragon_to_floor': {'roomId', 'index'},
    'visit_tower_floor': {'roomId', 'index'},
    'complete_tutorial': {'fullyViewed'},
    'redeem_code': {'code'},
  };
}
