/// Protocol identities shared by the client journal and server evaluator.
/// No score, grant, entitlement or settlement command is accepted here.
abstract final class GameCommandSchema {
  static const keys = <String, Set<String>>{
    'refresh': {},
    'purchase_portrait_chest': {},
    'purchase_title_chest': {},
    'purchase_music_chest': {},
    'purchase_furniture': {'catalogId'},
    'purchase_relic': {'relic'},
    'open_chests': {'tier', 'count'},
    'open_special_chests': {'catalogId', 'count'},
    'use_relic': {'relic', 'dragonId'},
    'use_astral_lens': {'eggId'},
    'tag_egg': {'eggId', 'tagged'},
    'return_egg': {'eggId', 'sinisterConfirmed'},
    'craft_altar_relic': {'relic'},
    'use_altar_relic': {'relic', 'eggId'},
    'use_chronoshard': {'reductionPercent'},
    'use_wayfinder': {'kind', 'replaceAdventureId'},
    'equip_twinstar': {'dragonId'},
    'equip_relic': {'relic', 'dragonId'},
    'activate_egg': {'eggId'},
    'hatch_egg': {'eggId'},
    'name_dragon': {'dragonId', 'name'},
    'evolve_dragon': {'dragonId'},
    'buy_starlight_treat': {'dragonId'},
    'release_dragon': {'dragonId'},
    'start_adventure': {'adventureId', 'dragonId'},
    'dismiss_adventure': {'adventureId'},
    'claim_adventure': {'runId'},
    'abort_adventure': {'runId'},
    'dismiss_trial': {'offerId'},
    'claim_constellation': {},
    'unlock_room': {'roomId'},
    'build_floor': {'roomId'},
    'repair_floor': {'index'},
    'upgrade_ward': {},
    'complete_tutorial': {'fullyViewed'},
    'redeem_code': {'code'},
  };
}
