import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

/// Builds the same reviewed Dart rules for the trusted Edge worker. Generated
/// files contain no credentials, account saves or runtime seeds. CI builds them
/// from its exact checkout immediately before deployment.
Future<void> main(List<String> args) async {
  if (args.isNotEmpty) throw ArgumentError('This builder takes no arguments');
  final directory = Directory('supabase/functions/execute-game-command');
  final bundle = File('${directory.path}/game.generated.js');
  final bridge = File('${directory.path}/bundle.generated.ts');
  // Never let a failed compilation leave a deployable stale bridge.
  if (bridge.existsSync()) await bridge.delete();
  final result = await Process.run(Platform.resolvedExecutable, [
    'compile',
    'js',
    '-O2',
    '--no-source-maps',
    '-o',
    bundle.path,
    'tool/server_game_entry.dart',
  ]);
  if (result.exitCode != 0) {
    stderr.write(result.stderr);
    throw StateError('Server game compilation failed');
  }
  final bytes = await bundle.readAsBytes();
  if (bytes.length > 2 * 1024 * 1024) {
    throw StateError('Server game bundle exceeds budget');
  }
  final digest = sha256.convert(bytes).toString();
  await bridge.writeAsString(
      '''// Generated by tool/build_server_game.dart; do not edit.
import './game.generated.js';
export const ruleset = '$digest';
export async function evaluate(input: Record<string, unknown>): Promise<unknown> {
  const domain = globalThis as unknown as {
    dragonhavenGameCommand: (value: string) => Promise<string>;
  };
  return JSON.parse(await domain.dragonhavenGameCommand(JSON.stringify(input)));
}
''');
  stdout.writeln(jsonEncode(
      {'protocol': 2, 'rulesetSha256': digest, 'bundleBytes': bytes.length}));
}
